### ISSUE TITLE
Cannot change contents in the static folder

### ISSUE THREAD

**Issue by loongruige** [Varkaria/guweb#52]
**Describe the bug**
When I try to change files on the static folder, the files I change won't take effect.

**To reproduce**
1. Go to folder "static"
2. For example, change the mascot from "css/pages/home.css"
3. Restart server
4. Clear browser cache, try different network, try different device but it wont change
5. Try the same for mascot images
6. Won't work
7. Changing through styling from the template HTMLs, works in that case

**Additional context**
When new files are added, they are still visible

**Comment by cmyui** [comment]
Hey, when you try directly opening the edited files under /static/ in your browser, are you able to see the changes? (e.g. https://your-site.com/static/css/pages/home.css)

I did a quick read through the code and it looks like it _should_ work, so it _sounds_ like some sort of cache but I see you cleared your browser cache. Maybe Cloudflare cache? It's worth checking the http headers on the response when requesting those files, cloudflare or other caching layers on the server-side will respond with a header, something like `Cf-Cache-Status: HIT`:

![image](https://i.cmyui.xyz/cncp7Vo7yVYd5xatbbtLGw.png)

**Comment by loongruige** [comment]
Thank you for your response. As it seems, when accessed directly, the files won't change when directly viewed.
![image](https://github.com/varkaria/guweb/assets/72699183/47d74322-2b93-46c0-a90b-e76f952687ac)
Upon further inspection, Cf-Cache indeed returns HIT, I will try tinkering with Cloudflare, and will update if it will be fixed.

**Comment by loongruige** [comment]
This issue has been resolved.

The solution is to disable caching through Cloudflare, it's not an issue related to guweb. Thanks for your help.

For other users struggling with this error, in the domain settings, you should go to Rules > Page Rules and add a new rule for "\*your.domain/\*" (or "\*your.domain\*"), set Cache Level to bypass, and it will be ready to go.
![image](https://github.com/varkaria/guweb/assets/72699183/79045a66-aa31-4300-b1a4-8528a460b4aa)

**Comment by cmyui** [comment]
👍🏻 Nice work. If you're still interested in using cloudflare for caching (can be quite a good optimization), you'll _at least_ need to invalidate the cache for any modified files upon deployment of a new revision of your frontend.

There's a UI for this: 

![image](https://i.cmyui.xyz/sWnphBTvbZW_Po5y.png)

![image](https://i.cmyui.xyz/5zhWNkB5-Z150ooeGMNP0w.png)

Or alterantively in a more advanced deployment pipeline you may choose to do so programmatically to automate the full deployment sequence -- I think this is the invalidation API: https://developers.cloudflare.com/cache/how-to/purge-cache/purge-cache-key/
