### ISSUE TITLE
Development branch not working

### ISSUE THREAD

**Issue by xmtty** [Varkaria/guweb#7]
Whenever i use the development branch both the leaderboards and profiles are completely blank with no errors in console.

**Comment by ledlamp** [comment]
updated gulag and converted stats table?

**Comment by xmtty** [comment]
yes. fresh gulag install and converted stats table.

**Comment by JKBGL** [comment]
> yes. fresh gulag install and converted stats table.
Did you set up nginx correctly? guweb is using gulag's built-in api for retreiving scores and leaderboards.

**Comment by xmtty** [comment]
im fairly sure i did. i'll go through the nginx setup process again.

**Comment by xmtty** [comment]
![image](https://user-images.githubusercontent.com/58812660/127321909-203c03ca-3452-4bd9-94a8-d2fe6d73c80e.png)
this is the error i have been getting.

**Comment by JKBGL** [comment]
The error you are getting is unrelated to guweb.

It is related to nginx and you having set up your origin header policies incorrectly.
Are you hosting guweb and gulag on 2 different domains?

**Comment by JKBGL** [comment]
Try adding the header with nginx:
```
#put this in the osu.mty.systems server {} before the proxy redirects
add_header 'Access-Control-Allow-Origin' web.mty.systems;
```

**Comment by xmtty** [comment]
it has been fixed now. thank you.
